#!/usr/bin/env bash
# -*- coding: utf-8 -*-

post_install() {
  if [[ -e /usr/bin/big-wallpaper-random.flisol ]]; then
    if [[ -e /usr/bin/big-wallpaper-random ]]; then
      cp -f /usr/bin/big-wallpaper-random /usr/bin/big-wallpaper-random.bak
    fi
    cp -f /usr/bin/big-wallpaper-random.flisol /usr/bin/big-wallpaper-random
    chmod +x /usr/bin/big-wallpaper-random
  fi
}

post_upgrade() {
  post_install
}


